### ISSUE TITLE
Add some extra context for the template?

### ISSUE THREAD

**Issue by qur2** [hexojs/hexo-renderer-ejs#1]
Hi,
I'm trying to render an ejs template but it seems that I'm doing something wrong: I get no data passed to it. So I'm wondering what's the purpose of the ejs renderer if it gets not variables along (not even `page` or `site`).

My goal is to specify some json file to load in the front-matter (I figured I can easily do that using a `before_post_render` filter) and have this data available in the ejs template.
Is that doable? Are filters the good way to go?

Thanks for your help,
Aurélien.

**Comment by stevenjoezhang** [comment]
Hi, the easiest way to modify variables is to use the `template_locals` filter

https://hexo.io/api/filter#template-locals
