### ISSUE TITLE
Update ejs to 2.0?

### ISSUE THREAD

**Issue by NoahDragon** [hexojs/hexo-renderer-ejs#6]
For me, I think just simply increase the version number would be okay.

**Comment by yuri-karadzhov** [comment]
Is this repository still alive?

**Comment by NoahDragon** [comment]
@yuri-karadzhov, Yes.

**Comment by yuri-karadzhov** [comment]
It seems like no one maintain it at least for a year.

**Comment by NoahDragon** [comment]
Because the EJS is in version 2, and it is not backwards compatibility. For EJS version 1, this plugin is stable.

I have just created the EJS v2 renderer for Hexo. https://github.com/NoahDragon/hexo-renderer-ejs2

**Comment by yuri-karadzhov** [comment]
I know, but It's more common to raise version to `0.3.0` so it reflects braking changes. The wrapper around the renderer is primitive, and it's better not to create copies of pretty much the same package.

**Comment by NoahDragon** [comment]
Another reason that I made such copy is that @tommy351 hasn't maintained npm packages for a long while. To create a fresh new copy is a way to make the plugin maintainable.

**Comment by yuri-karadzhov** [comment]
That's what I'm talking about - repository is dead. I'm truing to ping maintainers of main hexo repository so they can support plugins too. But as all wrappers are primitive probably it's better to use common engine like [consolidate](https://github.com/tj/consolidate.js) to handle major renders at once.

**Comment by NoahDragon** [comment]
Good idea. Probably I could create one.

All the Hexo repos still maintained by Hexo members, only the NPM packages we couldn't do anything.

**Comment by yuri-karadzhov** [comment]
I would create one myself. So they should ping package holder to give them rights to publish.
